project:
  type: website

toc: true

number-sections: false

format:
  html:
    theme: lux
    css: style.css
    # page-layout: full

website:
  favicon: "images/elizabeth.jpg"
  site-url: "https://www.elizabethdonaldson.com"
  twitter-card: true
  image : "images/elizabeth.jpg"
  open-graph: true
  title: "Elizabeth Donaldson Homes"
  navbar:
    logo : "images/elizabeth.jpg"
    left:
      - index.qmd
    right:
      - icon : compass
        href : https://www.compass.com/agents/elizabeth-donaldson/
        aria-label: Compass
      - icon: facebook
        href: https://www.facebook.com/elizabeth.d.donaldson/
        aria-label: Facebook
      - icon: instagram
        href: https://www.instagram.com/donaldson_elizabeth/
        aria-label: Instagram

      - icon: linkedin
        href: https://www.linkedin.com/in/elizabeth-donaldson-71a9a051/
        aria-label: Linkedin

  google-analytics: "G-113GHEL4QB"

execute:
  freeze: auto

resources:
  - CNAME
